// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizAPI.Models;

#nullable disable

namespace QuizAPI.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizAPI.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TimeTaken")
                        .HasColumnType("int");

                    b.HasKey("ParticipantId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("QuizAPI.Models.Question", b =>
                {
                    b.Property<int>("QnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QnId"));

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option4")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QnInWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("QnId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QnId = 1,
                            Answer = 3,
                            Option1 = "Hyper Trainer Marking Language",
                            Option2 = "Hyper Text Marketing Language",
                            Option3 = "Hyper Text Markup Language",
                            Option4 = "Hyper Text Markup Leveler",
                            QnInWords = "What does HTML stand for?"
                        },
                        new
                        {
                            QnId = 2,
                            Answer = 3,
                            Option1 = "ALU",
                            Option2 = "Memory",
                            Option3 = "CPU",
                            Option4 = "Control unit",
                            QnInWords = "The brain of any computer system is"
                        },
                        new
                        {
                            QnId = 3,
                            Answer = 2,
                            Option1 = "FORTRAN",
                            Option2 = "PROLOG",
                            Option3 = "C",
                            Option4 = "COBOL",
                            QnInWords = "Which of the following computer languages is used for artificial intelligence?"
                        },
                        new
                        {
                            QnId = 4,
                            Answer = 3,
                            Option1 = "Mathematical Mind",
                            Option2 = "Artistic mind",
                            Option3 = "Logical Mind",
                            Option4 = "Scientific Knowledge",
                            QnInWords = "What is the primary requisite of a good computer programmer?"
                        },
                        new
                        {
                            QnId = 5,
                            Answer = 3,
                            ImageName = "mouse.png",
                            Option1 = "Keyboard",
                            Option2 = "Monitor",
                            Option3 = "Mouse",
                            Option4 = "Graphics Card",
                            QnInWords = "Name the device."
                        },
                        new
                        {
                            QnId = 6,
                            Answer = 1,
                            Option1 = "Analytical Engine",
                            Option2 = "Calculator",
                            Option3 = "Processor",
                            Option4 = "Abacus",
                            QnInWords = "The first mechanical computer designed by Charles Babbage was called?"
                        },
                        new
                        {
                            QnId = 7,
                            Answer = 2,
                            Option1 = "4 bits",
                            Option2 = "8 bits",
                            Option3 = "16 bits",
                            Option4 = "32 bits",
                            QnInWords = "One byte is equivalent to?"
                        },
                        new
                        {
                            QnId = 8,
                            Answer = 3,
                            Option1 = "FTP",
                            Option2 = "UML",
                            Option3 = "HTML",
                            Option4 = "URL",
                            QnInWords = "Web pages are written using?"
                        },
                        new
                        {
                            QnId = 9,
                            Answer = 4,
                            Option1 = "Dos",
                            Option2 = "Unix",
                            Option3 = "Window NT",
                            Option4 = "CSS",
                            QnInWords = "Which of the following is NOT an operating system?"
                        },
                        new
                        {
                            QnId = 10,
                            Answer = 4,
                            Option1 = "Interface Program",
                            Option2 = "Interface Protocol",
                            Option3 = "Internet program",
                            Option4 = "Internet Protocol",
                            QnInWords = "What is the full form of IP?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
